name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        path: 'core'
    - name: Clone repository another repository
      uses: actions/checkout@v2
      with:
        repository: 'netresj/empty'
        path: 'empty'
    - name: Current working directory
      run: pwd
    - name: List Files
      run: ls -al

